---
title: "KNN and SVM"
author: "Thao Huynh"
date: "2023-04-26"
output: pdf_document
---

KNN
```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(ggplot2))
suppressMessages(library(class))
suppressMessages(library(dplyr))
# - `Production (000)` - `Production Share` - `Real-World CO2 (g/mi)` - `Real-World CO2_City (g/mi)` - `Real-World CO2_Hwy (g/mi)` - `HP/Engine Displacement` - `HP/Weight (lbs)` - `Ton-MPG (Real-World)` - `Average Number of Gears`

# Transforming Vehicle Type into Numeric Level
# 1 : All, 2 : Car SUV, 3 : Minivan/Van, 3 : Pickup, 4 : Sedan/Wagon, 5 : Truck SUV
carEmissions$`Vehicle Type` <- as.numeric(as.factor(carEmissions$`Vehicle Type`))
carEmissions$Manufacturer <- as.numeric(as.factor(carEmissions$Manufacturer))
carEmissions$`Model Year` <- as.numeric(as.factor(carEmissions$`Model Year`))
carEmissions$`Regulatory Class` <- as.numeric(as.factor(carEmissions$`Regulatory Class`))
carEmissions$`2-Cycle MPG`<- as.numeric(carEmissions$`2-Cycle MPG`)

carEmissions$Quartile<-as.factor(cut(carEmissions$`Real-World CO2 (g/mi)`,quantile(carEmissions$`Real-World CO2 (g/mi)`),include.lowest=TRUE,labels=FALSE))

throwaways <- c("Production (000)", "Production Share", "Real-World CO2 (g/mi)",
                                 "Real-World CO2_City (g/mi)", "Real-World CO2_Hwy (g/mi)", 
                                 "HP/Engine Displacement", "HP/Weight (lbs)", "Ton-MPG (Real-World)",
                                 "Average Number of Gears", "Real-World CO2 (g/mi)")

carEmissionsTrimmed <- dplyr::select(carEmissions, -one_of(throwaways))
carEmissionsTrimmed$`Vehicle Type` <- as.numeric(carEmissions$`Vehicle Type`)
carEmissionsTrimmed$Manufacturer <- as.numeric(carEmissions$Manufacturer)
carEmissionsTrimmed$`Model Year` <- as.numeric(carEmissions$`Model Year`)
carEmissionsTrimmed$`Regulatory Class` <- as.numeric(carEmissions$`Regulatory Class`)


# Splitting data
set.seed(1234)
training_pct <- 0.75
Z <- sample(nrow(carEmissionsTrimmed), training_pct*nrow(carEmissionsTrimmed))

Xtrain <-  data.frame(carEmissionsTrimmed[Z,]) 
Ytrain <-  carEmissionsTrimmed$Quartile[Z]
Xtest <-  tibble(carEmissionsTrimmed[-Z,])
Yhat <- knn(Xtrain, Xtest, Ytrain, k = 5, use.all = TRUE) 
Ytest <- carEmissionsTrimmed$Quartile[-Z]

# Initialize data
err_class <- rep(1:100)
tpr <- rep(1:100)
fpr <- rep(1:100)

# run the loop
for (k in 1:100){
  Yhat <- knn(Xtrain, Xtest, Ytrain, k = k, use.all = TRUE) 
  err_class[k] <- mean(Yhat != Ytest) # The prediction is not correct
  tpr[k] <- sum(Yhat == 1 & Ytest == 1) / sum(Ytest == 1) # TP/P
  fpr[k] <- sum(Yhat == 1 & Ytest == 0) / sum(Ytest == 0) # FP/N
}

ggplot(tibble(err_class, k = 1:100), aes(x = k, y = err_class)) +
  geom_line()

# K with lowest error classification
which.min(err_class) 

# Probability of a Mis-classification
err_class[which.min(err_class)] 

```






SVM: CLASSIFYING BY MANUFACTURER

```{r}
suppressMessages(library(e1071))
suppressMessages(library(tidyverse))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))

carEmissions$'Vehicle Type' <- as.factor(carEmissions$'Vehicle Type')
carEmissions$Manufacturer <- as.factor(carEmissions$Manufacturer)
carEmissions$`2-Cycle MPG`<- as.numeric(carEmissions$`2-Cycle MPG`)

# SVM Equation
SVM <- svm(Quartile ~ . - `Production (000)` -  `Production Share` - `Real-World CO2 (g/mi)` - 
                      `Real-World CO2_City (g/mi)` - `Real-World CO2_Hwy (g/mi)` -
                      `HP/Engine Displacement` - `HP/Weight (lbs)` - 
                      `Ton-MPG (Real-World)` - `Average Number of Gears` - `Real-World CO2 (g/mi)`, 
           data = carEmissions, kernel = "linear")


# Coefficient Matrix
Yhat <- predict(SVM)
table(Yhat, carEmissions$Quartile)


# Tuning SVM based on the Kernel
set.seed(123)
SVMtuning <- tune(svm, Quartile ~ . - `Production (000)` -  `Production Share` - `Real-World CO2 (g/mi)` - 
                      `Real-World CO2_City (g/mi)` - `Real-World CO2_Hwy (g/mi)` -
                      `HP/Engine Displacement` - `HP/Weight (lbs)` - 
                      `Ton-MPG (Real-World)` - `Average Number of Gears` - `Real-World CO2 (g/mi)`, 
                  data = carEmissions,
                  ranges = list(kernel = c("linear", "polynomial", "radial",
                                       "sigmoid")))
SVMtuning # will provide the kernel providing the best performance

# Classification Error Rate
1 - SVMtuning$best.performance

# We can look at how kernel each performed in terms of the prediction error rate using
summary(SVMtuning)
plot(SVMtuning)

```




Trees
```{r}
library(randomForest)
set.seed(123)
carEmissionsTrimmed$`Vehicle Type` <- as.factor(carEmissions$`Vehicle Type`)
carEmissionsTrimmed$Manufacturer <- as.factor(carEmissions$Manufacturer)
carEmissionsTrimmed$`Model Year` <- as.factor(carEmissions$`Model Year`)
carEmissionsTrimmed$`Regulatory Class` <- as.factor(carEmissions$`Regulatory Class`)

BAG <- randomForest(Quartile ~ . - `Model Year`,
                    data = carEmissionsTrimmed[Z,])
BAG
```












